<template>
  <div style="height: 100%;">
    <b-modal id="deleteAllModal" title="Reset database" @ok="resetDB" no-fade>
      <p class="my-4">Are you sure you want to permanently delete all of your data?</p>
    </b-modal>
    <objects-table ref="table" :object="tableRows" :links="tableLinks" :showAdd="false" :selectable="false" thClass="hidden_header" :crumbs="crumbs">
      <template v-slot:header>
        <button @click="resetDBPrompt">Reset DB...</button>
      </template>
    </objects-table>
    <!-- <b-card bg-variant="light" title="Welcome" style="max-width: 40rem; margin-top: 1rem;">
      <b-card-text>
        Save or skip links, and get new link recommendations based on your history.
      </b-card-text>
      <b-card-text> A <b>Profile</b> is a collection of links and sources for links. </b-card-text>
      <b-card-text>
        A <b>Source</b> is a link that provides link recommendations. Sources have a score (points) - the more points, the more often they offer suggestions.
      </b-card-text>
      <b-card-text> A <b>Link</b> is a reference to a webpage, and is either saved or not. </b-card-text>
    </b-card> -->
  </div>
</template>

<script>
import { DB_NAME, dbPromise } from '../../../store/Constants.ts';
import * as idb from '../../../store/idb.js';
import { deleteDB } from 'idb';
import ObjectsTable from '../components/ObjectsTable.vue';

export default {
  name: 'Home',
  components: {
    ObjectsTable,
  },
  data() {
    return {
      tableRows: [
        {
          name: 'Profiles',
          description: 'Profiles are a combination of links and sources.',
        },
        {
          name: 'Scrapers',
          description: 'A scraper is code for extracting links and sources from webpages from a certain domain.',
        },
        {
          name: 'Settings',
          description: 'Everything else.',
        },
      ],
      tableLinks: {
        Profiles: '#/profiles?filters=autoGenerated,eq,false',
        Scrapers: '#/scrapers',
        Settings: '#/settings',
      },
    };
  },
  computed: {
    crumbs() {
      return [
        {
          text: 'Home',
          href: '#/',
        },
      ];
    },
    numProfiles() {
      return this.$store.state.profiles.length;
    },
    numProfilesText() {
      return this.numProfiles > 0 ? '(' + this.numProfiles + ')' : '';
    },
  },
  methods: {
    resetDBPrompt() {
      this.$bvModal.show('deleteAllModal');
    },
    async resetDB() {
      // await dbPromise.close();
      // let delDBRequest = window.indexedDB.deleteDatabase(DB_NAME);
      // delDBRequest.onsuccess = function(event) {
      //   debugger;
      //   idb.fetchProfiles();
      // }
      // delDBRequest.onerror = function(event) {
      //   debugger;
      // }
      await deleteDB(DB_NAME, {
        blocked() {
          debugger;
        },
      });
      await idb.fetchProfiles();
    },
  },
};
</script>

<style>
.hidden_header {
  display: none;
}
.breadcrumb {
  padding: 0.2rem 0.5rem !important;
}
</style>
