<template>
  <div style="height: 100%;">
    <b-modal id="addProfileModal" title="Add Profile" @ok="addProfile" no-fade>
      <div>
        <span>Name:</span>
        <input id="addProfileNameInput" type="text" v-on:keyup.enter="addProfile" />
      </div>
    </b-modal>
    <objects-table
      ref="table"
      :object="profiles"
      @create="addProfilePrompt"
      @click="openProfile"
      :ineditable-row-names="[]"
      :crumbs="crumbs"
      @deleteSelectedRows="deleteProfiles"
      :givenCols="['id', 'name', 'links', 'sources']"
    />
  </div>
</template>

<script>
import ObjectsTable from '../components/ObjectsTable.vue';
import * as idb from '../../../store/idb.js';

export default {
  name: 'Profiles',
  components: {
    ObjectsTable,
  },
  mounted() {
    this.fetchData();
  },
  computed: {
    profiles() {
      return this.$store.state.profiles;
    },
    crumbs() {
      return [
        {
          text: 'Home',
          href: '#/',
        },
        {
          text: 'Profiles',
          href: '#/profiles?filters=autoGenerated,eq,false',
        },
      ];
    },
  },
  methods: {
    deleteProfiles(selection) {
      for (let i in selection) {
        idb.deleteProfile({
          profileId: selection[i].id,
        });
      }
    },
    fetchData() {
      idb.fetchProfiles();
    },
    addProfilePrompt() {
      this.$bvModal.show('addProfileModal');
    },
    addProfile() {
      this.$bvModal.hide('addProfileModal');
      let nameInput = document.getElementById('addProfileNameInput').value;
      if (nameInput.length < 1) {
        return;
      }
      let profile = {
        name: nameInput,
        autoGenerated: false,
      };
      idb.addProfile(profile);
    },
    openProfile({ item, index, event }) {
      this.$router.push({ name: 'profile', params: { id: item.id } });
    },
  },
};
</script>
