<template>
  <div>
    <b-modal id="addProfileModal" title="Add Profile" @ok="addProfile">
      <div>
        <span>Name:</span>
        <input id="addProfileNameInput" type="text" />
      </div>
    </b-modal>
    <b-breadcrumb :items="crumbs" />
    <objects-table ref="table" :object="profiles" @create="addProfilePrompt" @click="openProfile" :ineditable-row-names="[]" />
  </div>
</template>

<script>
import ObjectsTable from '../components/ObjectsTable.vue';
import * as idb from '../../../store/idb.js';

export default {
  name: 'Profiles',
  components: {
    ObjectsTable,
  },
  mounted() {
    this.fetchData();
  },
  computed: {
    profiles() {
      return this.$store.state.profiles;
    },
    crumbs() {
      return [
        {
          text: 'Home',
          href: '#/',
        },
        {
          text: 'Profiles',
          href: '#/profiles',
        },
      ];
    },
  },
  methods: {
    fetchData() {
      idb.fetchProfiles();
    },
    addProfilePrompt() {
      this.$bvModal.show('addProfileModal');
    },
    addProfile() {
      let nameInput = document.getElementById('addProfileNameInput').value;
      if (nameInput.length < 1) {
        return;
      }
      let profile = {
        name: nameInput,
        autoGenerated: false,
      };
      idb.addProfile(profile);
    },
    openProfile({ item, index, event }) {
      this.$router.push({ name: 'profile', params: { id: item.id } });
    },
  },
};
</script>
