<template>
  <div style="height: 100%;">
    <b-modal size="xl" id="getSuggestionModal" title="Get Suggestion" no-fade>
      <button @click="drawSuggestion" :disabled="getSuggestionStatus === 'Loading...'">Get new suggestion</button>
      <p>Status: {{ getSuggestionStatus }}</p>
      <div>
        Result:
        <div v-for="(value, name) in getSuggestionResult" :key="name">{{ name }}: {{ value }}</div>
      </div>
      <div style="display: flex">
        <button @click="openSuggestion" :disabled="getSuggestionResult == null || getSuggestionResult.url == null">Open</button>
        <button @click="storeSuggestion('save')" :disabled="getSuggestionResult == null || getSuggestionResult.url == null">Save</button>
        <button @click="storeSuggestion('skip')" :disabled="getSuggestionResult == null || getSuggestionResult.url == null">Skip</button>
      </div>
    </b-modal>

    <b-modal id="deleteProfileModal" title="Delete Profile" @ok="deleteObject" no-fade>
      <p class="my-4">Are you sure you want to delete this profile?</p>
    </b-modal>
    <objects-table
      ref="table"
      :crumbs="crumbs"
      :object="profile"
      :ineditable-row-names="['id', 'name', 'autoGenerated', 'nextScrape', 'timeAdded']"
      :ineditable-col-names="['id', 'Links', 'Sources', 'Logs']"
      :rowDescriptions="{
        name: 'Display name',
        autoGenerated: 'Whether or not this profile was generated automatically from a webpage.',
        timeAdded: 'The time this profile was stored.',
        id: 'Unique identifier for this profile.',
        Links: 'Number of links stored for this profile.',
        Sources: 'Number of sources stored for this profile.',
        defaultLinkAction: `*save* to save pages as links when they are opened, *skip* to skip them. Any other value does nothing.`,
        defaultSourceAction: `*save* to save pages as sources when they are opened, *skip* to skip them opened. Any other value does nothing.`,
      }"
      @save="saveObject"
      :fetchData="fetchData"
      @deleteObject="askDeleteObject"
      :links="fieldLinks"
      :givenRows="['id', 'name', 'Links', 'Sources', 'Logs']"
    >
      <template v-slot:header>
        <button @click="openSuggestionModal" title="Draw suggestion from this profile.">Get suggestion...</button>
        <button v-show="isAutoGenerated" @click="scrape" title="Open and scrape this profile for links.">Scrape</button>
        <button v-show="isAutoGenerated" @click="openLink(true)" title="Open this profile in a new tab.">Open</button>
        <button @click="exportProfile">Export</button>
      </template>
    </objects-table>
  </div>
</template>

<script>
import ObjectsTable from '../components/ObjectsTable.vue';
import * as idb from '../../../store/idb.js';
import { convertId } from '../../../Utils.js';

export default {
  name: 'Profile',
  components: {
    ObjectsTable,
  },
  watch: {
    '$route.params.id': function(id) {
      this.fetchData();
    },
  },
  data() {
    return {
      getSuggestionStatus: '',
      getSuggestionResult: '',
      profile: null,
    };
  },
  mounted() {
    this.fetchData();
  },
  methods: {
    openSuggestion() {
      chrome.tabs.create({ url: 'http://' + this.getSuggestionResult.url, active: true });
    },
    storeSuggestion(action) {
      idb.saveOrSkipLink({
        link: {
          url: this.getSuggestionResult.url,
          sources: [this.getSuggestionResult.profileId],
        },
        action,
        targetId: this.profileId,
      });
    },
    openSuggestionModal() {
      this.$bvModal.show('getSuggestionModal');
    },
    async drawSuggestion() {
      this.getSuggestionStatus = 'Loading...';
      this.getSuggestionResult = '';
      let suggestion = await idb.getSuggestion(this.profileId);
      this.getSuggestionStatus = 'Finished.';
      this.getSuggestionResult = suggestion;
    },
    openLink({ active }) {
      chrome.tabs.create({ url: 'http://' + this.profile.id, active });
    },
    async scrape() {
      chrome.runtime.sendMessage({ action: 'scrapeProfile', url: this.profile.id });
    },
    async exportProfile() {
      let csvContent = '';
      for (let i = 0; i < this.fieldNames.length; i++) {
        let fieldName = this.fieldNames[i];
        if (fieldName === 'profileId') {
          continue;
        }
        csvContent += fieldName + ': ' + this.profile[fieldName] + '\n';
      }
      let links = await idb.getLinks(this.profileId);
      let fieldNames = ['profileId', 'saved', 'url'];
      for (let i = 0; i < links.length; i++) {
        let link = links[i];
        for (let a in link) {
          if (!fieldNames.includes(a)) {
            fieldNames.push(a);
          }
        }
      }
      csvContent += 'LINKS\n';
      csvContent += fieldNames.join(',') + '\n';
      for (let i = 0; i < links.length; i++) {
        let link = links[i];
        let line = '';
        for (let j = 0; j < fieldNames.length; j++) {
          let fieldName = fieldNames[j];
          if (link[fieldName] !== undefined) {
            line += link[fieldName];
          }
          line += ',';
        }
        line += '\n';
        csvContent += line;
      }
      let sources = await idb.getProfileSources(this.profileId);
      let sourceFieldNames = ['consumerId', 'providerId', 'saved', 'points'];
      for (let i = 0; i < sources.length; i++) {
        let source = sources[i];
        for (let a in source) {
          if (!sourceFieldNames.includes(a)) {
            sourceFieldNames.push(a);
          }
        }
      }
      csvContent += 'SOURCES\n';
      csvContent += sourceFieldNames.join(',') + '\n';
      for (let i = 0; i < sources.length; i++) {
        let source = sources[i];
        let line = '';
        for (let j = 0; j < sourceFieldNames.length; j++) {
          let fieldName = sourceFieldNames[j];
          if (source[fieldName] !== undefined) {
            line += source[fieldName];
          }
          line += ',';
        }
        line += '\n';
        csvContent += line;
      }
      let prefix = 'data:text/csv;charset=utf-8,';
      const data = prefix + encodeURIComponent(csvContent);
      const link = document.createElement('a');
      link.setAttribute('href', data);
      link.setAttribute('download', this.profileName + '.csv');
      link.click();
    },
    askDeleteObject() {
      this.$bvModal.show('deleteProfileModal');
    },
    async saveObject() {
      await idb.storeProfile(this.profile, { overwriteProps: true, keepExistingProps: false });
      this.fetchData();
    },
    deleteObject() {
      idb.deleteProfile({
        profileId: this.$route.params.id,
      });
      this.$router.push({ name: 'profiles' });
    },
    async fetchData() {
      this.profile = await idb.loadProfile({ profileId: this.profileId });
      this.$refs.table.changesPending = false;
    },
  },
  computed: {
    isAutoGenerated() {
      if (this.profile != null) {
        return this.profile.autoGenerated;
      }
      return false;
    },
    fieldLinks() {
      return {
        Links: '#/profile/' + encodeURIComponent(this.$route.params.id) + '/links?filters=saved,eq,true',
        Sources: '#/profile/' + encodeURIComponent(this.$route.params.id) + '/sources',
        Logs: '#/logs?filters=objectType,eq,Profile]]objectKeys,eq,' + encodeURIComponent(this.$route.params.id) + ']]',
      };
    },
    canAddProperty() {
      return this.filter != null && this.filter.length > 0 && (this.profile == null || this.profile[this.filter] == null);
    },
    profileId() {
      return convertId(this.$route.params.id);
    },
    profileName() {
      if (this.profile == null) {
        return '';
      }
      if (typeof this.profile.name === 'object') {
        return JSON.stringify(this.profile.name);
      }
      if (this.profile.name == null || this.profile.name === '') {
        return decodeURIComponent(this.profile.id);
      }
      return this.profile.name;
    },
    profileStats() {
      return this.$store.state.profileStats;
    },
    numProps() {
      return this.profile == null ? 0 : Object.keys(this.profile).length;
    },
    numLinks() {
      if (this.profileStats == null) {
        return 0;
      }
      return this.profileStats.numLinks;
    },
    numSources() {
      if (this.profileStats == null) {
        return 0;
      }
      return this.profileStats.numSources;
    },
    fields() {
      let out = [];
      for (let i = 0; i < this.fieldNames.length; i++) {
        let fieldName = this.fieldNames[i];
        out.push({
          name: fieldName,
          value: this.profile[fieldName],
        });
      }
      return out;
    },
    removableFieldNames() {
      let out = [];
      for (let i in this.fieldNames) {
        let fieldName = this.fieldNames[i];
        if (!['id', 'name'].includes(fieldName)) {
          out.push(fieldName);
        }
      }
      return out;
    },
    fieldNames() {
      let out = [];
      for (let a in this.profile) {
        out.push(a);
      }
      return out;
    },
    crumbs: function() {
      return [
        {
          text: 'Home',
          href: '#/',
        },
        {
          text: 'Profiles',
          href: '#/profiles?filters=autoGenerated,eq,false',
        },
        {
          text: this.profileName,
          href: '#/profile/' + encodeURIComponent(this.profileId),
        },
      ];
    },
  },
};
</script>
