<template>
  <div style="height: 100%;">
    <b-modal id="addSourceModal" title="Add Source" @ok="addSource" no-fade>
      <div>
        <span>id/url:</span>
        <input id="addSourceIdInput" type="text" v-on:keyup.enter="addSource" />
      </div>
      <div>
        <span>points:</span>
        <input id="addSourcePointsInput" type="number" min="0" value="0" v-on:keyup.enter="addSource" />
      </div>
    </b-modal>
    <objects-table
      ref="table"
      :object="sources"
      @create="addSourcePrompt"
      @click="openSource"
      :colNamesToSkip="['consumerId']"
      :colLabels="{ providerId: 'Profile' }"
      :crumbs="crumbs"
      @deleteSelectedRows="deleteSources"
      :givenCols="['points', 'saved', 'providerId', 'timeAdded']"
      sortBy="points"
      :sortDesc="true"
    />
  </div>
</template>

<script>
import ObjectsTable from '../components/ObjectsTable.vue';
import * as idb from '../../../store/idb.js';
import { Source } from '../../../models/Source.js';
import { convertId } from '../../../Utils.js';

export default {
  name: 'ProfilePage',
  components: {
    ObjectsTable,
  },
  watch: {
    '$route.params.id': function() {
      this.fetchData();
    },
  },
  mounted() {
    this.fetchData();
  },
  methods: {
    deleteSources(selection) {
      for (let i in selection) {
        idb.deleteProfileSource({
          profileId: selection[i].consumerId,
          sourceId: selection[i].providerId,
        });
      }
    },
    fetchData() {
      idb.loadSources({ profileId: this.profileId });
      idb.loadProfile({ profileId: this.profileId });
    },
    addSourcePrompt() {
      this.$bvModal.show('addSourceModal');
    },
    async addSource() {
      this.$bvModal.hide('addSourceModal');
      let urlInput = document.getElementById('addSourceIdInput').value;
      if (urlInput.length < 1) {
        return;
      }
      let source = Source(urlInput, this.profileId);
      source.points = document.getElementById('addSourcePointsInput').value;
      source.autoGenerated = true;
      await idb.addSources({ sources: [source] });
      this.fetchData();
    },
    openSource({ item, index, event }) {
      this.$router.push({ name: 'profileSource', params: { profileId: this.profileId, sourceId: item.providerId } });
    },
  },
  computed: {
    sources() {
      return this.$store.state.sources;
    },
    numSources: function() {
      return Object.keys(this.sources).length;
    },
    profileId() {
      return convertId(this.$route.params.id);
    },
    profile() {
      return this.$store.state.profile;
    },
    profileName() {
      if (this.profile == null) {
        return '';
      }
      if (typeof this.profile.name === 'object') {
        return JSON.stringify(this.profile.name);
      }
      if (this.profile.name == null || this.profile.name === '') {
        return decodeURIComponent(this.profile.id);
      }
      return this.profile.name;
    },
    crumbs: function() {
      return [
        {
          text: 'Home',
          href: '#/',
        },
        {
          text: 'Profiles',
          href: '#/profiles?filters=autoGenerated,eq,false',
        },
        {
          text: this.profileName,
          href: '#/profile/' + encodeURIComponent(this.profileId),
        },
        {
          text: 'Sources',
          href: '#/profile/' + encodeURIComponent(this.profileId) + '/sources',
        },
      ];
    },
  },
};
</script>
