<template>
  <div>
    <b-breadcrumb :items="crumbs" />
    <objects-table ref="table" :object="sources" @create="addSource" @click="openSource" :colNamesToSkip="['consumerId']" :colLabels="{ providerId: 'Profile' }" />
  </div>
</template>

<script>
import ObjectsTable from '../components/ObjectsTable.vue';
import * as idb from '../../../store/idb.js';
import { Source } from '../../../models/Source.js';
import { convertId } from '../../../Utils.js';

export default {
  name: 'ProfilePage',
  components: {
    ObjectsTable,
  },
  watch: {
    '$route.params.id': function() {
      this.fetchData();
    },
  },
  mounted() {
    this.fetchData();
  },
  methods: {
    fetchData() {
      idb.loadSources({ profileId: this.profileId });
      idb.loadProfile({ profileId: this.profileId });
    },
    async addSource(inputStr) {
      let source = Source(inputStr, this.profileId);
      source.points = 1;
      source.autoGenerated = true;
      await idb.addSources({ sources: [source] });
      this.fetchData();
    },
    openSource({ item, index, event }) {
      this.$router.push({ name: 'profileSource', params: { profileId: this.profileId, sourceId: item.providerId } });
    },
  },
  computed: {
    sources() {
      return this.$store.state.sources;
    },
    numSources: function() {
      return Object.keys(this.sources).length;
    },
    profileId() {
      return convertId(this.$route.params.id);
    },
    profile() {
      return this.$store.state.profile;
    },
    profileName() {
      return this.profile == null ? '' : this.profile.name;
    },
    crumbs: function() {
      return [
        {
          text: 'Home',
          href: '#/',
        },
        {
          text: 'Profiles',
          href: '#/profiles',
        },
        {
          text: this.profileName,
          href: '#/profile/' + encodeURIComponent(this.profileId),
        },
        {
          text: 'Sources',
          href: '#/profile/' + encodeURIComponent(this.profileId) + '/sources',
        },
      ];
    },
  },
};
</script>
